### ISSUE TITLE
Afficher tout type de valeur dans les résultats de biologie 

### ISSUE THREAD

**Issue by elsiehoffet-94** [arkhn-oss/Cohort360#101]
## Description
Pour le moment, seulement les attributs de type ValueQuantity sont affichés correctement dans les résultats de bio, alors qu'il existe des résultats de type ValueString, ValueBoolean, ValueRatio etc.. 

En particulier, on a besoin de résultats de type ValueString pour un type de résultats spécifique.

**Comment by MiskoG** [comment]
Alright, so I checked Cohort and it seems that the current behaviour is as followed (screenshot from demo env)

![image](https://user-images.githubusercontent.com/7942024/119631927-a613c600-be10-11eb-8f75-143e962cbed3.png)

- If the Observation has a _valueQuantity_ attribute, display its value and unit (first line in the example)
- If the Observation doesn't have a _valueQuantity_ but have an _interpretation_ attribute, display it (second line with "S")

What I suggest for now is handling this attributes

![image](https://user-images.githubusercontent.com/7942024/119632502-26d2c200-be11-11eb-841d-566ca2ca6e7f.png)

Using this logic in front 

- If there is a _valueQuantity_, show it (value + unit)
- If there is a _valueString_, show the string
- If there is a _valueBoolean_, show TRUE or FALSE
- If there is a _valueInteger_, show the integer
- If there is an _interpretation_, show it

I intentionally didn't say "else if" but "if-s" just to avoid missing some information if an Observation happen to have several of these attributes. This could lead to a situation where there are multiple values displayed in a single line. We will see in reality if this happens and how to handle it properly.

**Comment by elsiehoffet-94** [comment]
Seems like a good approach! I think we will face other issues in the near future but it's a good start :)

**Comment by nriss** [comment]
I agree, it seems great! According to me, the interpretation attribute must be shown somewhere else (maybe on result hover ?)
But showing everything is clearly a good start !

**Comment by tevariou** [comment]
> I agree, it seems great! According to me, the interpretation attribute must be shown somewhere else (maybe on result hover ?)
> But showing everything is clearly a good start !

so what do I do for the interpretation result ? I can display a supplementary column for this

**Comment by tevariou** [comment]
> Using this logic in front
> 
> * If there is a _valueQuantity_, show it (value + unit)
> * If there is a _valueString_, show the string
> * If there is a _valueBoolean_, show TRUE or FALSE
> * If there is a _valueInteger_, show the integer
> * If there is an _interpretation_, show it
> 
> I intentionally didn't say "else if" but "if-s" just to avoid missing some information if an Observation happen to have several of these attributes. This could lead to a situation where there are multiple values displayed in a single line. We will see in reality if this happens and how to handle it properly.

you can't have multiple kinds of value according to the spec

**Comment by nriss** [comment]
Right! But you can have a value and an interprétation, so multiple results to show

**Comment by elsiehoffet-94** [comment]
I think your PR is sufficient for now. 
Interpretations could appear somewhere else, on-click or on hover for instance. This would depend on user feedback I guess? 
We will also have to handle component attributes, (when we have multiple results like diastolic + systolic blood pressure), but it's not a huge priority. We can create an issue and investigate solutions ?
