### ISSUE TITLE
Biology Result - Value String

### ISSUE THREAD

**Issue by Peltier10** [arkhn-oss/Cohort360#102]
## Problem
In Ops-Rose database, biology results are string, without unit. 
ValueQuantity in the Observation Resource is the only value take in count in Biology Results in Cohort 360. 

## Description
Is it possible for the column "VALEUR" in Biology in Cohort 360 to take the input ValueQuantity or ValueString ? (FHIR required only one Value for each observation, with filters, Observation Resource has ValueQuantity filled or ValueString, not both at the same time). 

## Additional context
![image](https://user-images.githubusercontent.com/34452954/119628358-51bb1700-be0d-11eb-86a1-ee79f18658c9.png)

View in Cohort 360, 3rd line
![image](https://user-images.githubusercontent.com/34452954/119628529-7a431100-be0d-11eb-940d-9c81e0f82e23.png)

**Comment by nriss** [comment]
see https://github.com/arkhn/Cohort360/issues/101
