### ISSUE TITLE
[bug] Count de patients contradictoire dans la vue d'une cohorte existante ?

### ISSUE THREAD

**Issue by MiskoG** [arkhn-oss/Cohort360#65]
Exemple : https://demo.arkhn.com/cohort/cohort/12123/patients (se connecter en mode admin)

![image](https://user-images.githubusercontent.com/7942024/113739664-4a766780-9700-11eb-8036-4092dd12e208.png)

![image](https://user-images.githubusercontent.com/7942024/113739623-434f5980-9700-11eb-8f6c-4d79970c0097.png)

Le count global indique 112 patients sur la cohorte. 
Mais quand on regarde la répartition par périmètres, le tableau homme/femme/vivant/décédé, ou encore la liste des patients, on en voit 74 seulement.

Qui a raison ? 😎

**Comment by BPierrick** [comment]
C'est un comportement connu et "normal" en soit. Le count de la page principale est calculé à partir de la liste des members de la cohorte alors que celui de la liste des patients concerne les patients de la cohorte qui sont dans le périmètre du practitioner

**Comment by MiskoG** [comment]
Alors dans ce cas ok, mais d'après le 1er screenshot je n'ai que 4 périmètres et déjà accès aux 4.
Est-ce qu'il y a en fait plus de périmètres, mais ils ne sont pas affichés ?

**Comment by BPierrick** [comment]
Effectivement là il s'agit d'un comportement bizarre

**Comment by MiskoG** [comment]
@BPierrick @tevariou 
Effectivement votre hypothèse de patients en double semble se confirmer.

Je choisis 6 périmètres, le count est à 166 patients

![image](https://user-images.githubusercontent.com/7942024/113752894-c75c0e00-970d-11eb-8ada-978b39549569.png)

![image](https://user-images.githubusercontent.com/7942024/113752950-d5119380-970d-11eb-96ac-d6db86d73d38.png)

J'ajoute un critère recherche textuelle du mot "pas", j'attends un peu... et là le count passe à 187 patients 😄 

![image](https://user-images.githubusercontent.com/7942024/113753067-f6727f80-970d-11eb-8bbe-1e6137b4f0d6.png)
