### ISSUE TITLE
[Vue patient] Ré-afficher l'onglet "Biologie"

### ISSUE THREAD

**Issue by MiskoG** [arkhn-oss/Cohort360#69]
![image](https://user-images.githubusercontent.com/7942024/113758640-6b48b800-9714-11eb-9df6-73fc405a7029.png)

My bad @BPierrick je t'avais proposé qu'on le cache/supprime pour simplifier la vue.
Emeric et Corne m'ont dit que cette info était assez importante alors je te propose qu'on ré-affiche l'onglet et les Observations qui étaient dedans (j'espère que c'est pas trop painful !).

Pour les GHM en revanche on peut bien les garder cachés/supprimés pour la démo.

**Comment by BPierrick** [comment]
@MiskoG Quel nom doit on mettre pour cet onglet ? Celui qui a été retiré avait un label `GHM`, il faudrait mettre `Biologie` à la place ?

**Comment by MiskoG** [comment]
Ah my bad, il y avait pas un onglet Biologie ? Au niveau du menu de dessus peut-être ? (avec Parcours Patient, Documents cliniques, PMSI)

**Comment by BPierrick** [comment]
J'ai bien peur que non.. :/

**Comment by MiskoG** [comment]
Oh je l'ai peut-être trouvé. @BPierrick Ça te dit quelque chose un component qui s'appelle **PatientLaboTable** ?
On l'a peut-être complètement supprimé dans un commit depuis le fork.

**Comment by BPierrick** [comment]
Would this panel be something like this ?

![Capture d’écran 2021-04-08 à 16 24 57](https://user-images.githubusercontent.com/12270309/114043914-0366ae80-9887-11eb-8eb8-623ec479b414.png)

**Comment by MiskoG** [comment]
Totally what I had in mind 👍 Did you just code it from scratch ?

**Comment by BPierrick** [comment]
Nope i adjusted it back to the codebase

**Comment by MiskoG** [comment]
Nice !! We can bring it back then, if it's okay for you
