### ISSUE TITLE
Criteria : CIM 9 instead of CIM 10

### ISSUE THREAD

**Issue by Peltier10** [arkhn-oss/Cohort360#94]
## Description
There is a problem in the front of Cohort : 
When we want to choose a Diagnostic Criteria for a cohort, we have the information that diagnosis come from CIM 9 and after, we see that the diagnosis is a CIM 10 Diagnosis. (See screenshot) 

## Reproduction
1. Create a cohorte
2. Choose diagnosis criteria
3. See the difference (CIM 9 / CIM 10) 

## Expectation
The same classification. 
The ValueSet is about CIM 9 (ICD 9). 

## Screenshots
![image](https://user-images.githubusercontent.com/34452954/118841488-a66c0880-b8c8-11eb-8bd2-7ca815ec5e00.png)
![image](https://user-images.githubusercontent.com/34452954/118841743-dadfc480-b8c8-11eb-8107-a8bad5bb4746.png)

## Environment
Dev, Ops-Rose

**Comment by nriss** [comment]
Originally, Cohort360 has been developed using mimic-iii, which uses icd-9 classification!
I think it's just hard written 'icd-9', there is just a text correction to do, maybe replace by 'icd-9/icd-10 code' ?

**Comment by MiskoG** [comment]
Je me permets de close l'issue car à priori fixée par la PR de Teva que l'on va déployer sous peu 🙂
