### ISSUE TITLE
Have a Cohort config file in order to choose which ValueSet we want to use

### ISSUE THREAD

**Issue by MiskoG** [arkhn-oss/Cohort360#99]
Linked with what have been discussed in https://github.com/arkhn/Cohort360/issues/93

![image](https://user-images.githubusercontent.com/7942024/119539767-e5003800-bd8c-11eb-822d-a8db324678e8.png)

For example here, we use by default a ValueSet with some ICD-9 codes suited for our Arkhn demo.
As the terminology and even the subset of codes used will be changing from one center to an other, it could be interesting to have a config file in Cohort repo specifying which ValueSet will be used.

**Comment by tevariou** [comment]
I've added an environment variable to set the condition valueset url.

**Comment by MiskoG** [comment]
Great ! 🎸
